(
  
  default_build                &&
  mkdir -p /usr/doc/$SPELL     &&
  cp lib.txt menu.txt /usr/doc/$SPELL
  
  #./configure --with-xinerama \
  #            $OPTS           &&
  #make                        &&
  #prepare_install             &&
  #make    install  prefix=/usr

) > $C_FIFO 2>&1