(

#    python setup.py build			&&
    prepare_install                 		&&
    python setup.py install                     &&
    mkdir -p /usr/share/$SPELL                  &&
    cp -R examples tests /usr/share/$SPELL

) > $C_FIFO 2>&1

