( 

   export PATH=/opt/lunar/gnome/2/bin:$PATH &&
   export PKG_CONFIG_PATH=/opt/lunar/gnome/2/lib/pkgconfig:$PKG_CONFIG_PATH &&
   OPTS="$OPTS --prefix=/opt/lunar/gnome/2" &&
   default_build

) > $C_FIFO 2>&1
