--- Makefile	2003-06-16 11:09:25.000000000 -0500
+++ Makefile.new	2003-10-18 02:49:10.000000000 -0500
@@ -34,9 +34,7 @@
 # Platform for binary installation.  If you are using one of the 
 # following operating systems you do not have to compile the package.
 
-PLATFORM = solaris
-#PLATFORM = irix
-#PLATFORM = linux
+PLATFORM = linux
 
 # The WordNet system must be installed in a directory hierarchy.
 # WN_ROOT is the root of the WordNet installation hierarchy.
@@ -62,7 +60,7 @@
 
 # Default installation paths
 
-WN_ROOT = /usr/local/WordNet-2.0
+WN_ROOT = /usr
 
 # By default, precompiled WordNet binaries are installed in 
 # $WN_ROOT/bin.  You may specify another location, such as /usr/local/bin.
@@ -76,7 +74,7 @@
 # the default location, you MUST set the environment variable 
 # WNSEARCHDIR, or the WordNet browser will not be able to run.
 
-WN_DICTDIR = $(WN_ROOT)/dict
+WN_DICTDIR = $(WN_ROOT)/share/dict
 
 # By default, installing the database files is done by copying them
 # from the "dict" subdirectory into WN_DICTDIR.  To save space, you
@@ -105,7 +103,7 @@
 # also installed in HTML and PDF formats in $WN_ROOT/doc.
 
 WN_MANDIR = $(WN_ROOT)/man
-WN_DOCDIR = $(WN_ROOT)/doc
+WN_DOCDIR = $(WN_ROOT)/doc/WordNet
 
 ##### Platform specific stuff (for compiling from source only) 
 ##### If you are not compiling WordNet 2.0, you do not have to change
@@ -117,11 +115,8 @@
 
 CC = gcc
 
-# Use this for Solaris
-LOCAL_LDFLAGS = -R/usr/openwin/lib:/usr/lib:/usr/local/lib
-
 # Use this for Irix and Linux
-#LOCAL_LDFLAGS = 
+LOCAL_LDFLAGS = 
 
 # "UNIX" must be defined for things to compile...
 
@@ -140,45 +135,18 @@
 # You also need to know where the Xll include files and libraries are
 # on your system.
 
-# For the Solaris build, these were used:
-
-TCL_INCDIR = /usr/local/include
-TCL_LIBDIR = /usr/local/lib
-TK_INCDIR = /usr/local/include
-TK_LIBDIR = /usr/local/lib
-X11_INCDIR = /usr/openwin/include
-X11_LIBDIR = /usr/openwin/lib
-
-# For the Irix build, these were used:
-
-#TCL_INCDIR = /usr/local/include
-#TCL_LIBDIR = /usr/local/lib
-#TK_INCDIR = /usr/local/include
-#TK_LIBDIR = /usr/local/lib
-#X11_INCDIR = /usr/include
-#X11_LIBDIR = /usr/lib32
-
 # For the Linux build, these were used:
 
-#TCL_INCDIR = /usr/include
-#TCL_LIBDIR = /usr/lib
-#TK_INCDIR = /usr/include
-#TK_LIBDIR = /usr/lib
-#X11_INCDIR = /usr/X11R6/include
-#X11_LIBDIR = /usr/X11R6/lib
-
-# Libraries needed for Solaris
-
-WNB_LIBS = -ltk8.3 -ltcl8.3 -lX11 -lm -lsocket -lnsl -ldl -lpthread
-
-# Libraries needed for Irix
-
-#WNB_LIBS = -Xlinker -B -Xlinker static -ltk -ltcl -Xlinker -B -Xlinker dynamic -lX11 -lm
-
+TCL_INCDIR = /usr/include
+TCL_LIBDIR = /usr/lib
+TK_INCDIR = /usr/include
+TK_LIBDIR = /usr/lib
+X11_INCDIR = /usr/X11R6/include
+X11_LIBDIR = /usr/X11R6/lib
 
 # Libraries needed for Linux
 
-#WNB_LIBS = -ltk -ltcl -lX11 -lm -lnsl -ldl -lpthread
+WNB_LIBS = -ltk -ltcl -lX11 -lm -lnsl -ldl -lpthread
 
 ###### Finally, the "make" targets ######
 
