(
  ./configure --prefix=/usr/X11R6            \
              $OPTS                          &&
  make                                       &&
  prepare_install                            &&
  make    install                           
  
) > $C_FIFO 2>&1