# This spell released under the terms of the GNU General Public License
# as they appear in http://www.gnu.org/licenses/gpl.txt
    patch -p1 < $SCRIPT_DIR/libggigcp_0.8.2_fmod_hotfix-1.diff &&
    default_build
