#!/bin/sh

### BEGIN INIT INFO
# Provides: sockd
# Required-Start: $syslog
# Required-Stop: kill
# Default-Start: 3 4 5
# Default-Stop:  0 6
# Short-Description: dante is a SOCKS proxy server
# Description: dante is a SOCKS proxy server
### END INIT INFO

. /lib/lsb/init-functions

SERV=/usr/sbin/sockd
NAME=sockd

start()  {
  log_warning_msg  "$NAME about to start"
  if start_daemon $SERV -D -f /etc/sockd.conf
  then  log_success_msg  "$NAME started"
  else  log_failure_msg  "$NAME not started"
  fi
}

stop()  {
  MSG="Stopping $NAME"
  pkill "$NAME" 2> /dev/null    
  log_success_msg "$MSG"
}

help()  {
  echo  "Usage:  $0  {start|stop|restart}"
}

case $1 in
    start)                       start  ;;
  restart)  stop  &&  sleep  1;  start  ;;
     stop)  stop                        ;;
        *)  help                        ;;
esac

