(

  default_build                             &&
  mkdir -p /usr/doc/$SPELL                  &&
  cp -R doc INSTALL README /usr/doc/$SPELL  &&
  mkdir -p /usr/share/$SPELL                &&
  cp -R cks.sql cks.conf html /usr/share/$SPELL

) > $C_FIFO 2>&1