(

  make                        &&
  prepare_install             &&
  install  -o root -g root -m 755 pg_designer /usr/bin &&
  mkdir -p /usr/doc/$SPELL    &&
  install  -o root -g root -m 755 README /usr/doc/$SPELL

) > $C_FIFO 2>&1