(
  make                          &&
  prepare_install               &&
  mkdir -p /usr/doc/$SPELL/     &&
  cp -p *.html /usr/doc/$SPELL/ &&
  install  -o root -g root -m 755  astyle  /usr/bin  

) > $C_FIFO 2>&1