(
  
  ./configure --prefix=/usr              \
              --with-xinerama            \
	      $OPTS                      &&
  make                                   &&
  prepare_install                        &&
  make install

) > $C_FIFO 2>&1