(

  make                                                      &&
  prepare_install                                           &&
  install  -o root -g root -m 755  mindless        /usr/bin &&
  install  -o root -g root -m 755  $SCRIPT_DIR/mindless_magic  /usr/bin

) > $C_FIFO 2>&1