(

  default_build
#  ./configure --with-xinerama \
#              $OPTS           &&
#  make                        &&
#  prepare_install             &&
#  make    install  prefix=/usr

) > $C_FIFO 2>&1