(
  
  make                                       &&
  prepare_install                            &&
  install  -o root -g root -m 755  driftnet  /usr/bin &&
  install  -o root -g root -m 644 driftnet.1 /usr/man/man1
  
) > $C_FIFO 2>&1