(

if [ ! -e /usr/lib/gkrellm/plugins ]; then
   mkdir -p /usr/lib/gkrellm/plugins
fi                                                           &&
make                                                         &&
prepare_install                                              &&
make  install

  ) > $C_FIFO 2>&1

