--- Makefile.orig	2004-04-21 12:33:08.000000000 -0500
+++ Makefile	2004-04-21 12:38:18.000000000 -0500
@@ -9,9 +9,9 @@
 #CFLAGS=-DCHM_MT -DCHM_USE_PREAD -DCHM_USE_IO64
 CFLAGS=-DCHM_MT -DCHM_USE_PREAD -DCHM_USE_IO64 -g -DDMALLOC_DISABLE
 LDFLAGS=-lpthread
-INSTALLPREFIX=/usr/local/
-CC=gcc-3.2
-LD=gcc-3.2
+INSTALLPREFIX=/usr
+CC=gcc
+LD=gcc
 LIBTOOL=libtool
 CP=/bin/cp
 EXAMPLES=test_chmLib enum_chmLib enumdir_chmLib chm_http extract_chmLib
@@ -21,10 +21,10 @@
 examples: ${EXAMPLES}
 
 %.lo: %.c
-	${LIBTOOL} ${CC} -c -o $@ $^ ${CFLAGS}
+	${LIBTOOL} --mode=compile ${CC} -c -o $@ $^ ${CFLAGS}
 
 libchm.la: chm_lib.lo lzx.lo
-	${LIBTOOL} ${LD} -o $@ $^ ${LDFLAGS} -rpath ${INSTALLPREFIX}/lib
+	${LIBTOOL} --mode=link ${LD} -o $@ $^ ${LDFLAGS} -rpath ${INSTALLPREFIX}/lib
 
 install: libchm.la
 	chmod a+r libchm.la
