(
  ./configure  --prefix=/usr            \
               --mandir=/usr/share      \
  make                                  &&
  prepare_install                       &&
  make    install

) > $C_FIFO 2>&1
