(

  ruby extconf.rb                               &&
  make                                          &&
  prepare_install                               &&
  make    install                               &&                      
  cp -r sample /usr/share/doc/ruby-gtk/
  
) > $C_FIFO 2>&1